# Generated by Django 3.2.4 on 2021-06-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210629_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('email', models.CharField(default='', max_length=65)),
                ('address', models.CharField(default='', max_length=65)),
                ('addressline2', models.CharField(default='', max_length=65)),
                ('city', models.CharField(default='', max_length=65)),
                ('state', models.CharField(default='', max_length=65)),
                ('zip', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
    ]
