# Generated by Django 3.2.4 on 2021-06-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='items_json',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='address',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='state',
            field=models.CharField(max_length=65),
        ),
    ]
