# Generated by Django 3.2.4 on 2021-06-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210630_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='items_json',
            field=models.CharField(max_length=5000),
        ),
    ]
